### ISSUE TITLE
Missing DrugBank ID for Some Drug SMILES 

### ISSUE THREAD

**Issue by mintambrosia** [LabWeng/MeTDDI#2]
Dear author,
I am working with the DrugBank Version 5.1.8 dataset and trying to match the SMILES strings of 1409 drugs to their corresponding DrugBank IDs. However, I encountered an issue where some of the SMILES strings in dataset do not have a corresponding DrugBank ID. Could you kindly provide a mapping of SMILES to DrugBank IDs for these 1409 drugs?

Thank you for your support!

**Comment by LabWeng** [comment]
Thanks for raising this issue. You can check the attached file for mapping SMILES to DrugBank IDs for the 1409 drugs.
[single_drug_info.csv](https://github.com/user-attachments/files/17407708/single_drug_info.csv)
